### ISSUE TITLE
Invalid operands of type pointer<int64> and triton.language.int32

### ISSUE THREAD

**Issue by Sh3lock** [goombalab/hydra#11]
Thanks for the great work.

I had the following error when replacing the SS2D module in my model with Hydra.My block looks like the one below. I printed it and found that the first block worked fine, but when the input reached the Hydra module of the second block, the error occurred.Looking forward to your generous help!!

![block](https://github.com/user-attachments/assets/f88074ad-913d-4341-a86d-5920b49661dc)

```
Traceback (most recent call last):
  File "/home/lthpc/miniconda3/envs/ltf_mamba/lib/python3.10/site-packages/triton/compiler/code_generator.py", line 1124, in ast_to_ttir
    generator.visit(fn.parse())
  File "/home/lthpc/miniconda3/envs/ltf_mamba/lib/python3.10/site-packages/triton/compiler/code_generator.py", line 1017, in visit
    ret = super().visit(node)
  File "/home/lthpc/miniconda3/envs/ltf_mamba/lib/python3.10/ast.py", line 418, in visit
    return visitor(node)
  File "/home/lthpc/miniconda3/envs/ltf_mamba/lib/python3.10/site-packages/triton/compiler/code_generator.py", line 293, in visit_Module
    ast.NodeVisitor.generic_visit(self, node)
  File "/home/lthpc/miniconda3/envs/ltf_mamba/lib/python3.10/ast.py", line 426, in generic_visit
    self.visit(item)
  File "/home/lthpc/miniconda3/envs/ltf_mamba/lib/python3.10/site-packages/triton/compiler/code_generator.py", line 1017, in visit
    ret = super().visit(node)
  File "/home/lthpc/miniconda3/envs/ltf_mamba/lib/python3.10/ast.py", line 418, in visit
    return visitor(node)
  File "/home/lthpc/miniconda3/envs/ltf_mamba/lib/python3.10/site-packages/triton/compiler/code_generator.py", line 362, in visit_FunctionDef
    self.visit_compound_statement(node.body)
  File "/home/lthpc/miniconda3/envs/ltf_mamba/lib/python3.10/site-packages/triton/compiler/code_generator.py", line 288, in visit_compound_statement
    ret_type = self.visit(stmt)
  File "/home/lthpc/miniconda3/envs/ltf_mamba/lib/python3.10/site-packages/triton/compiler/code_generator.py", line 1017, in visit
    ret = super().visit(node)
  File "/home/lthpc/miniconda3/envs/ltf_mamba/lib/python3.10/ast.py", line 418, in visit
    return visitor(node)
  File "/home/lthpc/miniconda3/envs/ltf_mamba/lib/python3.10/site-packages/triton/compiler/code_generator.py", line 414, in visit_Assign
    values = self.visit(node.value)
  File "/home/lthpc/miniconda3/envs/ltf_mamba/lib/python3.10/site-packages/triton/compiler/code_generator.py", line 1017, in visit
    ret = super().visit(node)
  File "/home/lthpc/miniconda3/envs/ltf_mamba/lib/python3.10/ast.py", line 418, in visit
    return visitor(node)
  File "/home/lthpc/miniconda3/envs/ltf_mamba/lib/python3.10/site-packages/triton/compiler/code_generator.py", line 940, in visit_Call
    return self.call_JitFunction(fn, args, kws)
  File "/home/lthpc/miniconda3/envs/ltf_mamba/lib/python3.10/site-packages/triton/compiler/code_generator.py", line 908, in call_JitFunction
    generator.visit(fn.parse())
  File "/home/lthpc/miniconda3/envs/ltf_mamba/lib/python3.10/site-packages/triton/compiler/code_generator.py", line 1017, in visit
    ret = super().visit(node)
  File "/home/lthpc/miniconda3/envs/ltf_mamba/lib/python3.10/ast.py", line 418, in visit
    return visitor(node)
  File "/home/lthpc/miniconda3/envs/ltf_mamba/lib/python3.10/site-packages/triton/compiler/code_generator.py", line 293, in visit_Module
    ast.NodeVisitor.generic_visit(self, node)
  File "/home/lthpc/miniconda3/envs/ltf_mamba/lib/python3.10/ast.py", line 426, in generic_visit
    self.visit(item)
  File "/home/lthpc/miniconda3/envs/ltf_mamba/lib/python3.10/site-packages/triton/compiler/code_generator.py", line 1017, in visit
    ret = super().visit(node)
  File "/home/lthpc/miniconda3/envs/ltf_mamba/lib/python3.10/ast.py", line 418, in visit
    return visitor(node)
  File "/home/lthpc/miniconda3/envs/ltf_mamba/lib/python3.10/site-packages/triton/compiler/code_generator.py", line 362, in visit_FunctionDef
    self.visit_compound_statement(node.body)
  File "/home/lthpc/miniconda3/envs/ltf_mamba/lib/python3.10/site-packages/triton/compiler/code_generator.py", line 288, in visit_compound_statement
    ret_type = self.visit(stmt)
  File "/home/lthpc/miniconda3/envs/ltf_mamba/lib/python3.10/site-packages/triton/compiler/code_generator.py", line 1017, in visit
    ret = super().visit(node)
  File "/home/lthpc/miniconda3/envs/ltf_mamba/lib/python3.10/ast.py", line 418, in visit
    return visitor(node)
  File "/home/lthpc/miniconda3/envs/ltf_mamba/lib/python3.10/site-packages/triton/compiler/code_generator.py", line 303, in visit_Return
    ret_value = self.visit(node.value)
  File "/home/lthpc/miniconda3/envs/ltf_mamba/lib/python3.10/site-packages/triton/compiler/code_generator.py", line 1017, in visit
    ret = super().visit(node)
  File "/home/lthpc/miniconda3/envs/ltf_mamba/lib/python3.10/ast.py", line 418, in visit
    return visitor(node)
  File "/home/lthpc/miniconda3/envs/ltf_mamba/lib/python3.10/site-packages/triton/compiler/code_generator.py", line 934, in visit_Call
    args = [self.visit(arg) for arg in node.args]
  File "/home/lthpc/miniconda3/envs/ltf_mamba/lib/python3.10/site-packages/triton/compiler/code_generator.py", line 934, in <listcomp>
    args = [self.visit(arg) for arg in node.args]
  File "/home/lthpc/miniconda3/envs/ltf_mamba/lib/python3.10/site-packages/triton/compiler/code_generator.py", line 1017, in visit
    ret = super().visit(node)
  File "/home/lthpc/miniconda3/envs/ltf_mamba/lib/python3.10/ast.py", line 418, in visit
    return visitor(node)
  File "/home/lthpc/miniconda3/envs/ltf_mamba/lib/python3.10/site-packages/triton/compiler/code_generator.py", line 644, in visit_Compare
    return self._apply_binary_method(method_name, lhs, rhs)
  File "/home/lthpc/miniconda3/envs/ltf_mamba/lib/python3.10/site-packages/triton/compiler/code_generator.py", line 455, in _apply_binary_method
    return getattr(lhs, method_name)(rhs, _builder=self.builder)
  File "/home/lthpc/miniconda3/envs/ltf_mamba/lib/python3.10/site-packages/triton/language/core.py", line 30, in wrapper
    return fn(*args, **kwargs)
  File "/home/lthpc/miniconda3/envs/ltf_mamba/lib/python3.10/site-packages/triton/language/core.py", line 683, in __lt__
    return semantic.less_than(self, other, _builder)
  File "/home/lthpc/miniconda3/envs/ltf_mamba/lib/python3.10/site-packages/triton/language/semantic.py", line 420, in less_than
    input, other = binary_op_type_checking_impl(input, other, builder)
  File "/home/lthpc/miniconda3/envs/ltf_mamba/lib/python3.10/site-packages/triton/language/semantic.py", line 117, in binary_op_type_checking_impl
    check_ptr_type_impl(rhs_sca_ty, lhs_sca_ty, allow_rhs_ptr)
  File "/home/lthpc/miniconda3/envs/ltf_mamba/lib/python3.10/site-packages/triton/language/semantic.py", line 96, in check_ptr_type_impl
    raise IncompatibleTypeErrorImpl(type_a, type_b)
triton.language.semantic.IncompatibleTypeErrorImpl: invalid operands of type pointer<int64> and triton.language.int32

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lthpc/student/LiTengfei/RetinexMamba-main/basicsr/models/archs/RetinexMamba_arch.py", line 1167, in <module>
    print(f'GMac:{flops.total()/(1024*1024*1024)}')
  File "/home/lthpc/miniconda3/envs/ltf_mamba/lib/python3.10/site-packages/fvcore/nn/jit_analysis.py", line 248, in total
    stats = self._analyze()
  File "/home/lthpc/miniconda3/envs/ltf_mamba/lib/python3.10/site-packages/fvcore/nn/jit_analysis.py", line 551, in _analyze
    graph = _get_scoped_trace_graph(self._model, self._inputs, self._aliases)
  File "/home/lthpc/miniconda3/envs/ltf_mamba/lib/python3.10/site-packages/fvcore/nn/jit_analysis.py", line 176, in _get_scoped_trace_graph
    graph, _ = _get_trace_graph(module, inputs)
  File "/home/lthpc/miniconda3/envs/ltf_mamba/lib/python3.10/site-packages/torch/jit/_trace.py", line 1285, in _get_trace_graph
    outs = ONNXTracedModule(
  File "/home/lthpc/miniconda3/envs/ltf_mamba/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/lthpc/miniconda3/envs/ltf_mamba/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/lthpc/miniconda3/envs/ltf_mamba/lib/python3.10/site-packages/torch/jit/_trace.py", line 133, in forward
    graph, out = torch._C._create_graph_by_tracing(
  File "/home/lthpc/miniconda3/envs/ltf_mamba/lib/python3.10/site-packages/torch/jit/_trace.py", line 124, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "/home/lthpc/miniconda3/envs/ltf_mamba/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/lthpc/miniconda3/envs/ltf_mamba/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1568, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/home/lthpc/miniconda3/envs/ltf_mamba/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1508, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/lthpc/student/LiTengfei/RetinexMamba-main/basicsr/models/archs/RetinexMamba_arch.py", line 1154, in forward
    out = self.body(x)
  File "/home/lthpc/miniconda3/envs/ltf_mamba/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/lthpc/miniconda3/envs/ltf_mamba/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1568, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/home/lthpc/miniconda3/envs/ltf_mamba/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1508, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/lthpc/miniconda3/envs/ltf_mamba/lib/python3.10/site-packages/torch/nn/modules/container.py", line 215, in forward
    input = module(input)
  File "/home/lthpc/miniconda3/envs/ltf_mamba/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/lthpc/miniconda3/envs/ltf_mamba/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1568, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/home/lthpc/miniconda3/envs/ltf_mamba/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1508, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/lthpc/student/LiTengfei/RetinexMamba-main/basicsr/models/archs/RetinexMamba_arch.py", line 1112, in forward
    output_img = self.denoiser(img)
  File "/home/lthpc/miniconda3/envs/ltf_mamba/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/lthpc/miniconda3/envs/ltf_mamba/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1568, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/home/lthpc/miniconda3/envs/ltf_mamba/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1508, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/lthpc/student/LiTengfei/RetinexMamba-main/basicsr/models/archs/RetinexMamba_arch.py", line 1030, in forward
    fea = IGAB(fea)#调用IGAB的前馈网络,此时fea的大小不变
  File "/home/lthpc/miniconda3/envs/ltf_mamba/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/lthpc/miniconda3/envs/ltf_mamba/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1568, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/home/lthpc/miniconda3/envs/ltf_mamba/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1508, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/lthpc/student/LiTengfei/RetinexMamba-main/basicsr/models/archs/RetinexMamba_arch.py", line 710, in forward
    x_after_attn = self_attention(x_)  # b,hw,c
  File "/home/lthpc/miniconda3/envs/ltf_mamba/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/lthpc/miniconda3/envs/ltf_mamba/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1568, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/home/lthpc/miniconda3/envs/ltf_mamba/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1508, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/lthpc/student/LiTengfei/RetinexMamba-main/basicsr/models/archs/RetinexMamba_arch.py", line 572, in forward
    return hydra_split_conv1d_scan_combined(
  File "/home/lthpc/miniconda3/envs/ltf_mamba/lib/python3.10/site-packages/torch/autograd/function.py", line 539, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/home/lthpc/miniconda3/envs/ltf_mamba/lib/python3.10/site-packages/torch/cuda/amp/autocast_mode.py", line 113, in decorate_fwd
    return fwd(*args, **kwargs)
  File "/home/lthpc/student/LiTengfei/RetinexMamba-main/basicsr/models/archs/hydra/modules/ops.py", line 125, in forward
    scan = _mamba_chunk_scan_combined_fwd(
  File "/home/lthpc/miniconda3/envs/ltf_mamba/lib/python3.10/site-packages/mamba_ssm/ops/triton/ssd_combined.py", line 312, in _mamba_chunk_scan_combined_fwd
    dA_cumsum, dt = _chunk_cumsum_fwd(dt, A, chunk_size, dt_bias=dt_bias, dt_softplus=dt_softplus, dt_limit=dt_limit)
  File "/home/lthpc/miniconda3/envs/ltf_mamba/lib/python3.10/site-packages/mamba_ssm/ops/triton/ssd_chunk_state.py", line 675, in _chunk_cumsum_fwd
    _chunk_cumsum_fwd_kernel[grid_chunk_cs](
  File "/home/lthpc/miniconda3/envs/ltf_mamba/lib/python3.10/site-packages/triton/runtime/autotuner.py", line 100, in run
    timings = {config: self._bench(*args, config=config, **kwargs)
  File "/home/lthpc/miniconda3/envs/ltf_mamba/lib/python3.10/site-packages/triton/runtime/autotuner.py", line 100, in <dictcomp>
    timings = {config: self._bench(*args, config=config, **kwargs)
  File "/home/lthpc/miniconda3/envs/ltf_mamba/lib/python3.10/site-packages/triton/runtime/autotuner.py", line 83, in _bench
    return do_bench(kernel_call, warmup=self.warmup, rep=self.rep, quantiles=(0.5, 0.2, 0.8))
  File "/home/lthpc/miniconda3/envs/ltf_mamba/lib/python3.10/site-packages/triton/testing.py", line 104, in do_bench
    fn()
  File "/home/lthpc/miniconda3/envs/ltf_mamba/lib/python3.10/site-packages/triton/runtime/autotuner.py", line 81, in kernel_call
    self.fn.run(*args, num_warps=config.num_warps, num_stages=config.num_stages, **current)
  File "<string>", line 63, in _chunk_cumsum_fwd_kernel
  File "/home/lthpc/miniconda3/envs/ltf_mamba/lib/python3.10/site-packages/triton/compiler/compiler.py", line 476, in compile
    next_module = compile_kernel(module)
  File "/home/lthpc/miniconda3/envs/ltf_mamba/lib/python3.10/site-packages/triton/compiler/compiler.py", line 381, in <lambda>
    lambda src: optimize_ttir(ast_to_ttir(src, signature, configs[0], constants, debug=debug, arch=arch), arch))
  File "/home/lthpc/miniconda3/envs/ltf_mamba/lib/python3.10/site-packages/triton/compiler/code_generator.py", line 1133, in ast_to_ttir
    raise CompilationError(fn.src, node, repr(e)) from e
triton.compiler.errors.CompilationError: at 31:56:    pid_h = tl.program_id(axis=2)
    dt_ptr += pid_b * stride_dt_batch + pid_c * chunk_size * stride_dt_seqlen
    dt_out_ptr += pid_b * stride_dt_out_batch + pid_c * stride_dt_out_chunk
    dA_cumsum_ptr += pid_b * stride_dA_cs_batch + pid_c * stride_dA_cs_chunk

    offs_h = pid_h * BLOCK_SIZE_H + tl.arange(0, BLOCK_SIZE_H)
    offs_c = tl.arange(0, BLOCK_SIZE_CHUNK)
    dt_ptrs = dt_ptr + (offs_h[:, None] * stride_dt_head + offs_c[None, :] * stride_dt_seqlen)
    A_ptrs = A_ptr + offs_h * stride_A_head
    dt_out_ptrs = dt_out_ptr + (offs_h[:, None] * stride_dt_out_head + offs_c[None, :] * stride_dt_out_csize)
    dA_cs_ptrs = dA_cumsum_ptr + (offs_h[:, None] * stride_dA_cs_head + offs_c[None, :] * stride_dA_cs_csize)
    chunk_size_limit = min(chunk_size, seqlen - pid_c * chunk_size)
                                                        ^
IncompatibleTypeErrorImpl('invalid operands of type pointer<int64> and triton.language.int32') `
```

**Comment by sukjunhwang** [comment]
Hi, as this is a Triton error, could you check if it works if replacing Hydra to Mamba2?

**Comment by Sh3lock** [comment]
An error also occurred during the process of replacing Hydra with mamba2.I am a novice and I would like to ask if Hydra can be used directly in the CV field? The tensor shape I tried to input to Hydra was [B, H*W, C]. I apologize for the trouble caused by my stupidity!

```
return MambaSplitConv1dScanCombinedFn.apply(zxbcdt, conv1d_weight, conv1d_bias, dt_bias, A, D, chunk_size, initial_states, seq_idx, dt_limit, return_final_states, activation, rmsnorm_weight, rmsnorm_eps, outproj_weight, outproj_bias, headdim, ngroups, norm_before_gate)
  File "/home/lthpc/miniconda3/envs/ltf_mamba/lib/python3.10/site-packages/torch/autograd/function.py", line 539, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/home/lthpc/miniconda3/envs/ltf_mamba/lib/python3.10/site-packages/torch/cuda/amp/autocast_mode.py", line 113, in decorate_fwd
    return fwd(*args, **kwargs)
  File "/home/lthpc/miniconda3/envs/ltf_mamba/lib/python3.10/site-packages/mamba_ssm/ops/triton/ssd_combined.py", line 779, in forward
    causal_conv1d_cuda.causal_conv1d_fwd(rearrange(xBC, "b s d -> b d s"),
TypeError: causal_conv1d_fwd(): incompatible function arguments. The following argument types are supported:
    1. (arg0: torch.Tensor, arg1: torch.Tensor, arg2: Optional[torch.Tensor], arg3: Optional[torch.Tensor], arg4: bool) -> torch.Tensor

Invoked with: tensor([[[-0.0551, -0.0235,  0.0276,  ...,  0.1219, -0.2576, -0.0901],
         [ 0.3491,  0.0027, -0.2524,  ...,  0.1298, -0.1725, -0.3997],
         [-0.0929,  0.1811,  0.2437,  ..., -0.0911,  0.0448,  0.0189],
         ...,
         [ 0.1534, -0.0074,  0.1381,  ...,  0.1184,  0.0789,  0.0854],
         [-0.0417,  0.1837, -0.0028,  ...,  0.0472,  0.0744, -0.0814],
         [ 0.2981,  0.0212, -0.0718,  ...,  0.1671, -0.0092, -0.2625]]],
       device='cuda:0', requires_grad=True), tensor([[ 0.1369, -0.4054, -0.3088, -0.0985],
        [-0.3678, -0.2405,  0.0353,  0.0217],
        [ 0.2507,  0.2053,  0.3803,  0.2899],
        ...,
        [ 0.2608, -0.3699,  0.4976, -0.2181],
        [-0.0726,  0.0644,  0.2152,  0.1932],
        [ 0.0579,  0.1170, -0.2739, -0.0605]], device='cuda:0',
       grad_fn=<ViewBackward0>), Parameter containing:
tensor([-0.1367,  0.4649, -0.2984, -0.3938, -0.0692,  0.0953, -0.0778,  0.1326,
        -0.0542,  0.3738, -0.4041, -0.0206,  0.1791,  0.4109,  0.1747, -0.3994,
         0.3995, -0.2922,  0.0921, -0.0189,  0.2706,  0.1104,  0.0089, -0.4531,
        -0.2418,  0.2385,  0.3751,  0.3728,  0.0149,  0.4386, -0.2817,  0.2765,
         0.4668, -0.2755, -0.1964,  0.2250, -0.3544,  0.2785, -0.0469,  0.0784,
        -0.0236,  0.1902, -0.3843,  0.3978,  0.4412,  0.3485, -0.4582,  0.0759,
        -0.1680, -0.2987, -0.3881, -0.1405, -0.0498, -0.1522, -0.4821, -0.2683,
        -0.0691,  0.3659, -0.0963, -0.1640, -0.4317, -0.0695, -0.2244, -0.0033,
         0.3459,  0.0646, -0.2635, -0.0961, -0.1620,  0.2396,  0.1423,  0.2830,
         0.4077,  0.2432, -0.3143,  0.2378,  0.4647, -0.0859, -0.1539, -0.0118,
         0.2372, -0.2227,  0.3584, -0.1170,  0.1247, -0.4653,  0.4865, -0.3902,
        -0.1303, -0.4016,  0.3076, -0.3987, -0.1885, -0.4625,  0.3266, -0.2250,
        -0.1905, -0.1680, -0.0046,  0.4533, -0.2537,  0.0265,  0.3439, -0.2606,
         0.0397, -0.0631, -0.1450, -0.2250, -0.1856, -0.2079, -0.4959, -0.3376,
         0.0173,  0.2812,  0.1740, -0.3657, -0.2757,  0.4391,  0.2781, -0.0173,
        -0.1684,  0.0326, -0.1079, -0.4736,  0.4923, -0.4913,  0.1108, -0.2109,
         0.1411,  0.4001, -0.1172, -0.3068,  0.3666,  0.2470,  0.3209, -0.3527,
         0.2634, -0.1698,  0.3874, -0.4313,  0.4443,  0.3724,  0.3351,  0.1463,
         0.3244, -0.3742,  0.2425, -0.0921, -0.1148,  0.0099,  0.3235, -0.2732,
        -0.4393,  0.4802, -0.4005, -0.4202,  0.2116, -0.3074,  0.3713,  0.0234,
         0.0220, -0.0174,  0.3062, -0.2923,  0.4552, -0.2780,  0.0039,  0.2344,
        -0.4387,  0.3151,  0.1121,  0.4349, -0.3212,  0.2471,  0.1018,  0.2829,
        -0.2594,  0.2290,  0.2905,  0.3555,  0.2674, -0.1259,  0.1335,  0.1584,
         0.3314, -0.1510,  0.3499, -0.2358,  0.0364,  0.4216,  0.1721,  0.4261,
         0.3809,  0.3417, -0.4405, -0.0333,  0.1650,  0.2008, -0.4466, -0.0079,
         0.3868, -0.2359, -0.4430,  0.4732,  0.3293, -0.4311, -0.0407,  0.3823,
        -0.3213,  0.0595, -0.4153,  0.2447, -0.1272, -0.0787, -0.4108, -0.0557,
         0.2397,  0.0754,  0.3453, -0.0993, -0.3610, -0.0249, -0.4087, -0.4563,
         0.3722, -0.4680, -0.1683,  0.4787, -0.3674,  0.1380,  0.3567, -0.1024,
         0.4826,  0.1113,  0.0549,  0.0723, -0.0851,  0.1319,  0.4670,  0.1007,
        -0.1353,  0.3333,  0.2452,  0.2420,  0.2428,  0.0387,  0.1005, -0.2404,
        -0.4328, -0.0238, -0.1458,  0.2475,  0.3269,  0.0166, -0.3856,  0.4911],
       device='cuda:0', requires_grad=True), None, None, None, True
```
